class ChemAgentError(Exception): ...

class ChemAgentFatalError(ChemAgentError): ...

class ChemAgentGeneralError(ChemAgentError): ...


class ChemAgentToolNotWorkingError(ChemAgentGeneralError): ...

class ChemAgentToolProcessError(ChemAgentGeneralError): ...

class ChemAgentInputError(ChemAgentGeneralError): ...

class ChemAgentOutputError(ChemAgentGeneralError): ...

class ChemAgentSearchError(ChemAgentGeneralError): ...
